[package]
name = "craft-audiobook"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
structopt = "0.3.26"
tempfile = "3.5.0"
indicatif = "0.17.3"
tokio = { version = "1", features = ["full"] }
