[package]
name = "craft-audiobook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
structopt = "0.3.26"
tempfile = "3.5.0"
